/*

 MAP3.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 23 x 25
   Tile set      : tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map3Width 23
#define map3Height 25
#define map3Bank 0

extern unsigned char map3[];

/* End of MAP3.H */
