#ifndef ZGBMAIN_H
#define ZGBMAIN_H

#define STATES \
_STATE(STATE_MENU)\
_STATE(STATE_GAME)\
_STATE(STATE_GAME_OVER)\
STATE_DEF_END

#define SPRITES \
_SPRITE_DMG(SPRITE_PLAYER, player, 2, FRAME_16x16, 10)\
_SPRITE_DMG(SPRITE_SNAKE, snake, 2, FRAME_16x16, 1)\
_SPRITE_DMG(SPRITE_DOORS, doors, 2, FRAME_16x16, 6)\
SPRITE_DEF_END

#include "ZGBMain_Init.h"

#endif